### ISSUE TITLE
Vista compatibility mode

### ISSUE THREAD

**Issue by Irontobias** [rcojoe/barbiedolldupnailprinter#1]
I cant seem to get the x64 driver to install on win 10 even using Vista compatibility mode (on any service pack); it just errors out to the same code as before... 

Aside from that, have you had any luck editing the .dll to use the Lexmark cartridges as the user in the post had?

**Comment by rcojoe** [comment]
The (x64) driver was the toughest part. I was able to install it manually I believe.  

It looks like the DLL mod was left out of my explanation until I found it in the above WIKI. https://github.com/rcojoe/barbiedolldupnailprinter/wiki .  There are extensive logs in the barbie user folder that shows extactly what the driver is asking the printer, and how it is responding.  The correct responses are hardcoded in the DLL file.

I found the answer to the DLL in the Wiki above along with some log entries so you can use a string search and find the log file on your machine:  

> 
> So for everyone looking for a way to revive their Barbie Nail Printer for their kids and use a 43 cartridge, here is the quick and dirty way to do it:
> 
> Go to https://hexed.it/ Open a file:
> 
> Go to your barbie install directory: C:\Program Files (x86)\Mattel\Barbie Doll'd Up Nails
> 
> Load the file Models.dll into the hex editor.
> 
> Go to address 0x2A73. It should equal 78 now. Change it to 7E.
> 
> Now click Save As in the hexeditor and save it to your download folder.
> 
> Note: To copy the edited Models.dll file into the C:\Program Files (x86)\Mattel\Barbie Doll'd Up Nails directory, you need admin privileges.
> 
> Go to your C:\Program Files (x86)\Mattel\Barbie Doll'd Up Nails directory and move the Models.dll file to a safe place to keep the original.
> 
> Go to your download folder and Control-C Copy and then go to C:\Program Files (x86)\Mattel\Barbie Doll'd Up Nails directory and paste it into that folder.
> 
> That should be all you need to use the 43 Cartridge.
